name: "trigger-prefect-flow"
description: "triggers a prefect flow deployment"
inputs:
  deployment_name:
    description: "prefect cloud deployment name"
    required: true

  workspace_name:
    description: "Prefect cloud workspace name"
    required: true

  api_key:
    description: "Prefect cloud api key, please provide a secret"
    required: true
  
  params:
    description: "Prefect flow parameters (optional)"
    required: false
    default: '{}'

  wait:
    description: "Time in seconds to wait for the flow run to complete. Default is 0, 
    which means no waiting and this workflow will complete immediately after triggering 
    the prefect flow run."
    required: false
    default: '0'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: install prefect
      run: pip install 'prefect~=2.20.9'
      shell: bash

    - name: copy script into workspace
      run: cp "${GITHUB_ACTION_PATH}/prefect-run-deployment.py" .
      shell: bash

    - name: trigger prefect flow
      run: |
        prefect cloud login --key "${{ inputs.api_key }}" --workspace "${{ inputs.workspace_name }}"
        python prefect-run-deployment.py "${{ inputs.deployment_name }}" '${{ inputs.params }}' '${{ inputs.wait }}'
      shell: bash
