name: "trigger-prefect-flow"
description: "triggers a prefect flow deployment"
inputs:
  deployment_name:
    description: "prefect cloud deployment name"
    required: true

  workspace_name:
    description: "Prefect cloud workspace name"
    required: true

  api_key:
    description: "Prefect cloud api key, please provide a secret"
    required: true
  
  params:
    description: "Prefect flow parameters (optional)"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: install prefect
      run: pip install 'prefect~=2.20.9'
      shell: bash

    - name: trigger prefect flow
      run: |
        prefect cloud login --key "${{ inputs.api_key }}" --workspace "${{ inputs.workspace_name }}"
        python prefect-run-deployment.py "${{ inputs.deployment_name }}" '${{ inputs.params }}' 162000
      shell: bash
