on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  package_release:
    uses: landtechnologies/codeartifact-workflows/.github/workflows/package_release.yml@main
    secrets:
      CUSTOM_GITHUB_TOKEN: ${{ secrets.CI_USER_REPO_ACCESS }}